"""empty message

Revision ID: c8d5518eed70
Revises: b7f5f21feac0
Create Date: 2023-02-15 20:00:02.986643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d5518eed70'
down_revision = 'b7f5f21feac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Book', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'book', ['Book'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Book')

    # ### end Alembic commands ###
